/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Your Project API
 * Your project description
 * OpenAPI spec version: 1.0.0
 */
import * as axios from 'axios';
import type { AxiosRequestConfig, AxiosResponse } from 'axios';
import type { Project } from '../yourProjectAPI.schemas';

export const projectsList = <TData = AxiosResponse<Project[]>>(options?: AxiosRequestConfig): Promise<TData> => {
  return axios.default.get(`/api/projects/`, options);
};
export type ProjectsListResult = AxiosResponse<Project[]>;
