/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Your Project API
 * Your project description
 * OpenAPI spec version: 1.0.0
 */
export interface Task {
  /** @nullable */
  assignee?: number | null;
  readonly extra_field: number;
  /** @maxLength 255 */
  name: string;
  readonly pk: number;
  project: number;
}

export interface Project {
  readonly created_at: string;
  /**
   * @minimum -9223372036854776000
   * @maximum 9223372036854776000
   */
  department?: DepartmentEnum;
  readonly id: number;
  /** @maxLength 255 */
  name: string;
}

export interface PatchedTask {
  /** @nullable */
  assignee?: number | null;
  readonly extra_field?: number;
  /** @maxLength 255 */
  name?: string;
  readonly pk?: number;
  project?: number;
}

/**
 * * `1` - Main office
 * `2` - Secondary department
 */
export type DepartmentEnum = (typeof DepartmentEnum)[keyof typeof DepartmentEnum];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DepartmentEnum = {
  NUMBER_1: 1,
  NUMBER_2: 2,
} as const;
